### ISSUE TITLE
No explicit liscence declaration.

### ISSUE THREAD

**Issue by timoc** [skwp/git-workflows-book#8]
II would like to be able to use/mash this up to support an internal training initiative, but there is no explicit license (such as CC).

Can you clarify this?

**Comment by skwp** [comment]
hi Tim

That is great. 

I am cool with CC attribution. the book is slightly out of date with recent changes in git. if you do make any changes that would be useful to others I would love some pull requests!

## 

Yan Pritzker
reverb.com

From: Tim
Sent: Tuesday, December 17, 2013 11:45 AM
To: skwp/git-workflows-book
Subject: [git-workflows-book] No explicit liscence declaration. (#8)

II would like to be able to use/mash this up to support an internal training initiative, but there is no explicit license (such as CC).

Can you clarify this?

**Comment by skwp** [comment]
Added license

**Comment by timoc** [comment]
Cheers!

maybe you want to add the license info to the top or the bottom of the document too?
